service: cflow-shopping-cart
frameworkVersion: "3"

constructs:
  chargeFlowOrderStatusNotification:
    type: queue
    worker:
      handler: src/handlers/orderStatusNotification.main

package:
  individually: true

plugins:
  - serverless-pseudo-parameters
  - serverless-lift

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1

functions:
  chargeFlowProductCatalogService:
    handler: src/handlers/productCatalog.main
    events:
      - http:
          method: GET
          cors: true
          path: /products
          request:
            parameters:
              querystrings:
                pageNumber: true

  chargeFlowSingleProductCatalog:
    handler: src/handlers/singleProductCatalog.main
    events:
      - http:
          method: GET
          path: /product/{id}
          cors: true

  chargeFlowCartService:
    handler: src/handlers/cart.main
    events:
      - http:
          method: POST
          cors: true
          path: /cart

  chargeFlowOrderService:
    handler: src/handlers/order.main
    events:
      - http:
          method: POST
          cors: true
          path: /order
    environment:
      ORDER_STATUS_QUEUE_URL: ${construct:chargeFlowOrderStatusNotification.queueUrl}
